/** Just enough of each run to build the navigation: id, title, subtitle.
 *
 *  The nav needs three strings per run. Importing the full corpus to get them put 448 kB
 *  of entity tables into the entry chunk of every page, including the ones that show no
 *  runs at all. Generated by scripts/build-data.mjs alongside runs.json.
 */
import raw from "../../data/generated/runs_index.json";

export type RunSummary = { id: string; title: string; subtitle: string };
export const runsIndex = raw as unknown as RunSummary[];
