"""The derived checklist must stay derived, and must stay honest.

`docs/status.md` is generated by `tools/status.py`. The whole point of generating it is that a
hand-maintained checklist stops being true the moment it is committed — this repository has
been caught shipping that three times (audit A1, A28, A33). These tests guard the two ways a
generated checklist can still go wrong.
"""

from __future__ import annotations

import json
import pathlib
import re

import pytest

ROOT = pathlib.Path(__file__).resolve().parent.parent
STATUS = ROOT / "out" / "status.json"
DOC = ROOT / "docs" / "status.md"


def _load() -> dict:
    if not STATUS.exists():
        pytest.skip("out/status.json not present — run tools/status.py")
    return json.loads(STATUS.read_text(encoding="utf-8"))


def test_the_repository_does_not_contradict_the_disk() -> None:
    """No file may cite a path that does not resolve, or assert an absence that is present.

    Both had instances when this was written: `lib/palette.ts` cited a validator that was
    never in the repository, and `analyses/nf2_subgroup.py` logged that a 1.39 GB input had
    "not been fetched" while it sat in `data/depmap/`. Each sentence was true when written,
    which is exactly why nobody re-read it.
    """
    bad = _load()["contradictions"]
    assert not bad, "the repository contradicts the filesystem:\n  " + "\n  ".join(
        f"{r['kind']} {r['file']}:{r['line']} — {r['claim'][:100]}" for r in bad)


def test_the_document_is_not_hand_edited() -> None:
    """The rendered doc must match what the generator would produce right now.

    Compared on the tables rather than byte-for-byte, because the header carries a generation
    date that legitimately moves. If someone edits a number in `status.md` to make the
    checklist look better, this fails — which is the entire reason the file is generated.
    """
    if not DOC.exists():
        pytest.skip("docs/status.md not present")
    text = DOC.read_text(encoding="utf-8")
    counts = _load()["counts"]

    # Each headline number must appear inside the "At a glance" table. Matched as a bolded
    # number possibly followed by its unit (`**7 open**`) rather than as `**7**` exactly —
    # the first version of this test asserted the narrower pattern and failed on a correct
    # document, which is a guard that cries wolf and therefore gets deleted.
    glance = text.split("## Contradictions")[0]
    for key in ("stages", "auditOpen", "thresholds", "dataFiles"):
        assert re.search(rf"\*\*{counts[key]}[^*]*\*\*", glance), (
            f"{key}={counts[key]} does not appear in the summary of docs/status.md — the "
            "document has been edited by hand or is stale; re-run tools/status.py")


def test_every_threshold_that_gates_a_result_is_registered() -> None:
    """A threshold in the manifest is a threshold someone can audit. One that only exists as
    a constant in a module is a decision nobody can find."""
    s = _load()
    assert s["counts"]["thresholds"] >= 14, "thresholds disappeared from the manifest"
    for row in s["thresholds"]:
        assert row["justification"] in {"mechanistic", "empirical", "conventional"}, row


def test_no_emitted_dataset_is_shipped_and_ignored() -> None:
    """A payload emitted by the build and read by no component is dead weight that nothing
    reports: no error, no warning, just bytes in the bundle."""
    dead = [r["dataset"] for r in _load()["web"] if not r["consumed"]]
    assert not dead, f"datasets emitted but consumed by nothing: {dead}"
