/** Whose numbers these are — the population axis, read from the field nobody had opened.
 *
 *  Every other section of this atlas asks what is known about a disease. This one asks a
 *  question one level down: **about whom** is the number that is known. Orphanet stamps
 *  every prevalence record with a geography, eleven analytical layers were built on that
 *  corpus, and none of them had ever read the column.
 *
 *  THREE VIEWS, THREE QUESTIONS, and they are separate views rather than one long page
 *  because they are answered by different evidence and a reader should be able to disagree
 *  with one without discarding the others:
 *
 *    parity     Is the world's rare-disease epidemiology proportional to the world?  No.
 *    countries  Who, specifically, was looked at?                                    Not most people.
 *    spread     Does a disorder have *a* prevalence at all?                          Usually not.
 *
 *  THE BANNER IS NOT DECORATION. Geography is not ancestry, and a page about population
 *  structure that does not say so will be read as saying the opposite. It is rendered
 *  before the data in every view, and it is the analysis's own words rather than a
 *  paraphrase written here.
 */
import { useEffect, useMemo, useRef, useState } from "react";
import { EChart } from "../../../components/organisms/EChart";
import { categorical, chartInk, diverging, resolveMode } from "../../../lib/palette";
import { DATA_URL, useRemoteData } from "../../../lib/useRemoteData";
import { useHashParam } from "../../../lib/useHashParam";
import { useVirtualList } from "../../../lib/useVirtualList";
import {
  REGION_SLOT, bandColor, bandIndices, byDistanceFromParity, parityPhrase, placesByRarity,
  selectDiscordant, type AncestryGeography, type DiscordanceSort, type DiscordantRow,
} from "../ancestryModel";
import css from "./Ancestry.module.css";

const VIEWS = [
  { id: "parity", label: "Represented, against the world" },
  { id: "countries", label: "Who was looked at" },
  { id: "spread", label: "Prevalence is not one number" },
];

/** Row height and viewport are constants shared by the hook and the stylesheet. Two
 *  sources of truth for one measurement is how a virtual list ends up half a row out. */
const ROW_H = 52;
const LIST_H = 520;

const int = (n: number) => n.toLocaleString("en-US");

export function Ancestry() {
  const remote = useRemoteData<AncestryGeography>(DATA_URL("ancestry_geography"));
  const [view, setView] = useHashParam("a", "parity");

  if (remote.state === "loading") return <Skeleton />;
  if (remote.state === "error") {
    return (
      <div className={css.state} role="status">
        <span className={css.stateTitle}>The population dataset did not load</span>
        <p className={css.stateBody}>{remote.message}</p>
        <p className={css.stateBody}>
          It is fetched rather than bundled, so a bad deploy can 404 it while the rest of
          the page renders. Regenerate it and rebuild the explorer&rsquo;s data:
        </p>
        <code className={css.hint}>python tools/ancestry_geography.py</code>
      </div>
    );
  }

  const d = remote.data;
  if (!d.shape.records) {
    return (
      <div className={css.state}>
        <span className={css.stateTitle}>No population data has been generated yet</span>
        <code className={css.hint}>python tools/ancestry_geography.py</code>
      </div>
    );
  }

  return (
    <div className={css.root}>
      {/* Said before anything is shown, in the analysis's own words. */}
      <p className={css.caveat}>
        <span className={css.caveatTag}>read this first</span>
        {d.caveat}
      </p>

      <div className={css.viewNav} role="tablist" aria-label="Population views">
        {VIEWS.map((v) => (
          <button
            key={v.id}
            type="button"
            role="tab"
            aria-selected={view === v.id}
            className={view === v.id ? css.viewOn : css.view}
            onClick={() => setView(v.id)}
          >
            {v.label}
          </button>
        ))}
      </div>

      {view === "parity" && <Parity d={d} />}
      {view === "countries" && <Countries d={d} />}
      {view === "spread" && <Spread d={d} />}

      <p className={css.provenance}>
        Generated by <code>{d.generated}</code> from <code>{d.input}</code>.{" "}
        {d.authoredConstants.note}
      </p>
    </div>
  );
}

/* ------------------------------------------------------------------ view 1: parity ---- */

/** A diverging lollipop on a LOG axis, and the axis is the argument.
 *
 *  A representation ratio is multiplicative — 0.5 and 2.0 are the same distance from parity
 *  in opposite directions — so parity is log(1) = 0 and the encoding is genuinely diverging
 *  around it. On a linear axis Africa's 0.07 and Asia's 0.16 would both be indistinguishable
 *  stubs beside Europe's 8.10, which is to say the finding would be invisible in the chart
 *  that exists to show it.
 */
function Parity({ d }: { d: AncestryGeography }) {
  const rows = useMemo(() => byDistanceFromParity(d.regions), [d.regions]);
  const worst = rows[rows.length - 1];
  const best = rows[0];

  return (
    <>
      <div className={css.tiles}>
        <Tile
          label="Europe, against its share of people"
          value={`${best.representationRatio.toFixed(2)}×`}
          note={`${int(best.records)} records for ${(best.populationShare * 100).toFixed(1)}% of the world`}
          tone="over"
        />
        <Tile
          label="Africa, against its share of people"
          value={`${worst.representationRatio.toFixed(2)}×`}
          note={`${int(worst.records)} records for ${(worst.populationShare * 100).toFixed(0)}% of the world`}
          tone="under"
        />
        <Tile
          label="Between the two"
          value={`${Math.round(best.representationRatio / worst.representationRatio)}×`}
          note="the gap between the best- and worst-represented regions"
        />
        <Tile
          label="Records asserting “Worldwide”"
          value={`${Math.round(d.shape.worldwideShare * 100)}%`}
          note="a claim of population-independence, not a missing value"
          tone="warn"
        />
      </div>

      <div className={css.chart}>
      <EChart
        height={300}
        ariaLabel={
          "Representation ratio by world region, log axis, parity at one. " +
          rows.map((r) => `${r.region}: ${parityPhrase(r.representationRatio)}`).join(". ")
        }
        deps={[rows]}
        build={(mode) => {
          const ink = chartInk(mode);
          const div = diverging(mode);
          const over = div[div.length - 1];
          const under = div[0];
          const ordered = [...rows].reverse(); // ECharts y-axis draws bottom-up
          return {
            grid: { left: 176, right: 96, top: 28, bottom: 36 },
            xAxis: {
              type: "log",
              min: 0.05,
              max: 12,
              axisLine: { show: false },
              axisTick: { show: false },
              splitLine: { lineStyle: { color: ink.grid } },
              axisLabel: { color: ink.muted, formatter: (v: number) => `${v}×` },
            },
            yAxis: {
              type: "category",
              data: ordered.map((r) => r.region),
              axisLine: { show: false },
              axisTick: { show: false },
              axisLabel: { color: ink.text, fontSize: 13 },
            },
            tooltip: {
              trigger: "item",
              backgroundColor: ink.surface,
              borderColor: ink.grid,
              textStyle: { color: ink.text },
              formatter: (p: { dataIndex: number }) => {
                const r = ordered[p.dataIndex];
                return (
                  `<strong>${r.region}</strong><br/>` +
                  `${parityPhrase(r.representationRatio)}<br/>` +
                  `${int(r.records)} records — ${(r.recordShare * 100).toFixed(1)}% of placed<br/>` +
                  `${(r.populationShare * 100).toFixed(1)}% of the world's people`
                );
              },
            },
            series: [
              {
                // The stick, from parity to the value: the distance IS the finding, so it
                // is drawn rather than left for the reader to measure against a gridline.
                type: "bar",
                barWidth: 2,
                data: ordered.map((r) => ({
                  value: r.representationRatio,
                  itemStyle: { color: r.representationRatio >= 1 ? over : under, opacity: 0.45 },
                })),
                silent: true,
              },
              {
                type: "scatter",
                symbolSize: 15,
                data: ordered.map((r) => ({
                  value: [r.representationRatio, r.region],
                  itemStyle: { color: r.representationRatio >= 1 ? over : under },
                })),
                markLine: {
                  silent: true,
                  symbol: "none",
                  label: {
                    formatter: "parity",
                    color: ink.muted,
                    position: "end",
                    fontSize: 11,
                  },
                  lineStyle: { color: ink.muted, type: "dashed", width: 1 },
                  data: [{ xAxis: 1 }],
                },
                label: {
                  show: true,
                  position: "right",
                  distance: 10,
                  color: ink.text,
                  fontSize: 12,
                  formatter: (p: { dataIndex: number }) =>
                    ordered[p.dataIndex].representationRatio.toFixed(2) + "×",
                },
              },
            ],
          };
        }}
      />
      </div>

      <p className={css.reading}>
        Parity is <strong>1.0</strong>. Everything left of the dashed line is a population
        the world&rsquo;s reference rare-disease epidemiology has looked at less than its
        size warrants — and the axis is logarithmic, so the distance from{" "}
        <strong>{worst.representationRatio.toFixed(2)}</strong> to{" "}
        <strong>{best.representationRatio.toFixed(2)}</strong> is two orders of magnitude,
        not eight units. This is a measurement of publishing, not of disease.
      </p>
    </>
  );
}

/* --------------------------------------------------------------- view 2: countries ---- */

/** Every country that appears, priced per capita, on a log axis.
 *
 *  A count would rank countries by size, which nobody needed to be told. The rate is the
 *  question — and once it is a rate, the spread is four orders of magnitude and the axis
 *  has to be log for the same reason as the chart above.
 *
 *  Scatter with vertical jitter by region (a beeswarm without the packing cost): 130 points
 *  today, and the form does not degrade if the next source brings a thousand. Canvas
 *  renderer, so it does not degrade at ten thousand either.
 */
function Countries({ d }: { d: AncestryGeography }) {
  const [query, setQuery] = useState("");
  const q = query.trim().toLowerCase();
  const regions = useMemo(
    () => Array.from(new Set(d.perCapita.map((r) => r.region).filter(Boolean))) as string[],
    [d.perCapita]
  );

  const matches = q ? d.perCapita.filter((r) => r.country.toLowerCase().includes(q)) : [];

  return (
    <>
      <div className={css.tiles}>
        {d.disparity && (
          <>
            <Tile
              label="Most-covered population"
              value={`${int(Math.round(d.disparity.best.recordsPer100M))}`}
              note={`${d.disparity.best.country} — records per 100M people`}
              tone="over"
            />
            <Tile
              label="Least-covered population"
              value={d.disparity.worst.recordsPer100M.toFixed(1)}
              note={`${d.disparity.worst.country} — records per 100M people`}
              tone="under"
            />
            <Tile
              label="Between them"
              value={`${int(Math.round(d.disparity.ratio))}×`}
              note="and it is a ratio of who publishes epidemiology"
            />
          </>
        )}
        <Tile
          label="Countries appearing at all"
          value={int(d.shape.distinctCountries)}
          note={`out of ~195 — the rest are absent from the corpus entirely`}
          tone="warn"
        />
      </div>

      <div className={css.toolbar}>
        <label className={css.searchLabel} htmlFor="ancestry-country">
          Find a country
        </label>
        <input
          id="ancestry-country"
          className={css.search}
          type="search"
          value={query}
          placeholder="Nigeria, Brazil, Iceland…"
          onChange={(e) => setQuery(e.target.value)}
          autoComplete="off"
        />
        {q && (
          <span className={css.searchResult} role="status">
            {matches.length === 0
              ? "no country by that name has a single record"
              : matches
                  .slice(0, 3)
                  .map((m) => `${m.country}: ${m.recordsPer100M} per 100M (${m.records} records)`)
                  .join(" · ")}
          </span>
        )}
      </div>

      <div className={css.chart}>
      <EChart
        height={330}
        deps={[q]}
        ariaLabel={
          `Records per hundred million people for ${d.perCapita.length} countries, log axis, ` +
          `grouped by world region. The range runs from ${d.disparity?.worst.recordsPer100M} ` +
          `(${d.disparity?.worst.country}) to ${d.disparity?.best.recordsPer100M} (${d.disparity?.best.country}).`
        }
        build={(mode) => {
          const ink = chartInk(mode);
          const cat = categorical(mode);
          return {
            grid: { left: 176, right: 40, top: 20, bottom: 44 },
            xAxis: {
              type: "log",
              name: "prevalence records per 100M people",
              nameLocation: "middle",
              nameGap: 30,
              nameTextStyle: { color: ink.muted, fontSize: 11 },
              axisLine: { show: false },
              axisTick: { show: false },
              splitLine: { lineStyle: { color: ink.grid } },
              axisLabel: { color: ink.muted },
            },
            yAxis: {
              type: "category",
              data: regions,
              axisLine: { show: false },
              axisTick: { show: false },
              splitLine: { show: false },
              axisLabel: { color: ink.text, fontSize: 12 },
            },
            tooltip: {
              trigger: "item",
              backgroundColor: ink.surface,
              borderColor: ink.grid,
              textStyle: { color: ink.text },
              formatter: (p: { data: { c: PerCapitaPoint } }) => {
                const c = p.data.c;
                return (
                  `<strong>${c.country}</strong><br/>` +
                  `${c.recordsPer100M} records per 100M<br/>` +
                  `${int(c.records)} records · ${c.populationM}M people`
                );
              },
            },
            series: [
              {
                type: "scatter",
                symbolSize: (_v: unknown, p: { data: { c: PerCapitaPoint } }) =>
                  q && p.data.c.country.toLowerCase().includes(q) ? 16 : 9,
                data: d.perCapita
                  .filter((r) => r.region)
                  .map((r, i) => ({
                    // Deterministic jitter: a hash of the index, not Math.random, so the
                    // chart does not rearrange itself on every theme change or resize.
                    value: [r.recordsPer100M, r.region, jitter(i)],
                    c: r,
                    itemStyle: {
                      color: cat[REGION_SLOT[r.region as string] ?? 0],
                      opacity: q ? (r.country.toLowerCase().includes(q) ? 1 : 0.18) : 0.78,
                      borderColor: ink.surface,
                      borderWidth: 1,
                    },
                  })),
              },
            ],
          };
        }}
      />
      </div>

      <p className={css.reading}>
        Each dot is a country, placed by how many prevalence records it contributes per
        hundred million of its people.{" "}
        {d.countriesWithoutPopulation.length > 0 ? (
          <>
            {int(d.countriesWithoutPopulation.length)} further countries appear in the
            corpus without a population in the analysis&rsquo;s table and are excluded from
            the rate rather than silently given one.
          </>
        ) : (
          <>Every country in the corpus has a population in the table, so none is excluded.</>
        )}
      </p>
    </>
  );
}

type PerCapitaPoint = AncestryGeography["perCapita"][number];

/** Deterministic, evenly spread vertical offset within a band. */
function jitter(i: number): number {
  const x = Math.sin(i * 12.9898) * 43758.5453;
  return (x - Math.floor(x)) * 0.7 - 0.35;
}

/* ------------------------------------------------------------------ view 3: spread ---- */

/** The 386 disorders whose prevalence class is not the same in every country.
 *
 *  MASTER-DETAIL, NOT AN INLINE EXPANDER. At this length an expander moves every row below
 *  it and loses the reader's place; a detail panel beside the list keeps the position and
 *  keeps the row height fixed, which is also what lets the list be windowed.
 *
 *  The row's mark is a RANGE on the ordered rarity axis — the bands the disorder actually
 *  occupies, drawn against the same six-band scale for every row, so two rows are
 *  comparable at a glance. That is the whole reason the analysis ships `classOrder`.
 */
function Spread({ d }: { d: AncestryGeography }) {
  const [query, setQuery] = useState("");
  const [sort, setSort] = useState<DiscordanceSort>("span");
  const [selected, setSelected] = useState<string | null>(null);
  const listRef = useRef<HTMLDivElement>(null);
  // These marks are DOM, not canvas, so they cannot read the chart palette at paint time —
  // the mode has to be resolved and watched here, exactly as the EChart host does it.
  const mode = useThemeMode();

  const rows = useMemo(
    () => selectDiscordant(d.discordance.rows, { query, sort, minPlaces: 2 }),
    [d.discordance.rows, query, sort]
  );

  const focus = rows.find((r) => r.orpha === selected) ?? rows[0] ?? null;
  const focusIndex = focus ? rows.findIndex((r) => r.orpha === focus.orpha) : -1;
  const win = useVirtualList(rows.length, ROW_H, LIST_H);

  const move = (delta: number) => {
    if (!rows.length) return;
    const next = Math.min(rows.length - 1, Math.max(0, focusIndex + delta));
    setSelected(rows[next].orpha);
    win.scrollToIndex(next);
  };

  return (
    <>
      <div className={css.tiles}>
        <Tile
          label="Disorders whose prevalence class disagrees by country"
          value={`${d.discordance.discordant} of ${d.discordance.comparableDisorders}`}
          note={`${Math.round((d.discordance.share ?? 0) * 100)}% of every disorder where the comparison can be made`}
          tone="under"
        />
        <Tile
          label="Placed in exactly one country"
          value={int(d.concentration.disordersPlacedInExactlyOneCountry)}
          note="founder effect and single-report ascertainment look identical here"
        />
        <Tile
          label="With no placed record at all"
          value={int(d.concentration.disordersWithNoPlacedRecord)}
          note="every figure on this page is computed on the remainder"
          tone="warn"
        />
        <Tile
          label="The catalogue’s vocabulary for a population"
          value={`${d.specificPopulationTag.records} records`}
          note={`one untyped string, over ${d.specificPopulationTag.disorders} disorders`}
          tone="warn"
        />
      </div>

      <div className={css.toolbar}>
        <label className={css.searchLabel} htmlFor="ancestry-disorder">
          Search {d.discordance.rows.length} disorders
        </label>
        <input
          id="ancestry-disorder"
          className={css.search}
          type="search"
          value={query}
          placeholder="carnitine, amyloidosis, ORPHA code…"
          onChange={(e) => setQuery(e.target.value)}
          autoComplete="off"
        />
        <div className={css.sorts} role="group" aria-label="Sort disorders">
          {(
            [
              ["span", "Widest disagreement"],
              ["places", "Most countries"],
              ["name", "A–Z"],
            ] as [DiscordanceSort, string][]
          ).map(([id, label]) => (
            <button
              key={id}
              type="button"
              aria-pressed={sort === id}
              className={sort === id ? css.sortOn : css.sort}
              onClick={() => setSort(id)}
            >
              {label}
            </button>
          ))}
        </div>
      </div>

      <div className={css.split}>
        <div>
          <div className={css.scaleHead} aria-hidden="true">
            {d.classOrder.map((c) => (
              <span key={c} className={css.scaleTick}>
                {c.replace(/ /g, " ")}
              </span>
            ))}
          </div>

          {rows.length === 0 ? (
            <div className={css.emptyList} role="status">
              <span className={css.stateTitle}>No disorder matches “{query}”</span>
              <p className={css.stateBody}>
                Only disorders measured in more than one country can disagree, so the
                searchable set is {d.discordance.comparableDisorders}, not the whole
                catalogue.
              </p>
              <button type="button" className={css.sort} onClick={() => setQuery("")}>
                Clear the search
              </button>
            </div>
          ) : (
            <div
              ref={win.ref}
              className={css.list}
              style={{ height: LIST_H }}
              role="listbox"
              aria-label="Disorders with population-specific prevalence"
              aria-activedescendant={focus ? `disorder-${focus.orpha}` : undefined}
              tabIndex={0}
              onKeyDown={(e) => {
                if (e.key === "ArrowDown") { e.preventDefault(); move(1); }
                else if (e.key === "ArrowUp") { e.preventDefault(); move(-1); }
                else if (e.key === "Home") { e.preventDefault(); move(-rows.length); }
                else if (e.key === "End") { e.preventDefault(); move(rows.length); }
              }}
            >
              <div style={{ height: win.totalHeight, position: "relative" }}>
                <div style={{ transform: `translateY(${win.offsetY}px)` }} ref={listRef}>
                  {rows.slice(win.start, win.end).map((r) => (
                    <Row
                      key={r.orpha}
                      row={r}
                      classOrder={d.classOrder}
                      active={focus?.orpha === r.orpha}
                      mode={mode}
                      onSelect={() => setSelected(r.orpha)}
                    />
                  ))}
                </div>
              </div>
            </div>
          )}

          <p className={css.listNote}>
            Showing <strong>{int(rows.length)}</strong> of {d.discordance.rows.length}.
            Rows are windowed, so the list stays responsive when the next source multiplies
            it. Arrow keys move the selection.
          </p>
        </div>

        {focus && <Detail row={focus} classOrder={d.classOrder} mode={mode} />}
      </div>

      <p className={css.reading}>{d.discordance.says}</p>
    </>
  );
}

/** One disorder, as a range across the ordered rarity bands. */
function Row({
  row, classOrder, active, mode, onSelect,
}: {
  row: DiscordantRow; classOrder: string[]; active: boolean;
  mode: "light" | "dark"; onSelect: () => void;
}) {
  const bands = bandIndices(row, classOrder);
  const lo = bands[0] ?? 0;
  const hi = bands[bands.length - 1] ?? 0;
  const n = classOrder.length;

  return (
    <div
      id={`disorder-${row.orpha}`}
      role="option"
      aria-selected={active}
      className={active ? css.rowOn : css.row}
      style={{ height: ROW_H }}
      onClick={onSelect}
    >
      <span className={css.rowName} title={row.name}>{row.name}</span>
      <span className={css.track} aria-hidden="true">
        <span
          className={css.range}
          style={{ left: `${(lo / n) * 100}%`, width: `${((hi - lo + 1) / n) * 100}%` }}
        />
        {bands.map((b) => (
          <span
            key={b}
            className={css.band}
            style={{ left: `${((b + 0.5) / n) * 100}%`, background: bandColor(b, n, mode) }}
          />
        ))}
      </span>
      <span className={css.rowMeta}>
        <strong>{row.spanBands ?? "—"}</strong> bands · {row.places} countries
      </span>
    </div>
  );
}

/** The selected disorder, broken out by country. */
function Detail({
  row, classOrder, mode,
}: { row: DiscordantRow; classOrder: string[]; mode: "light" | "dark" }) {
  const places = useMemo(() => placesByRarity(row, classOrder), [row, classOrder]);
  return (
    <aside className={css.detail} aria-live="polite">
      <span className={css.detailEyebrow}>ORPHA:{row.orpha}</span>
      <h4 className={css.detailTitle}>{row.name}</h4>
      <p className={css.detailLede}>
        Measured in <strong>{row.places}</strong> countries, and reported in{" "}
        <strong>{row.classes.length}</strong> different prevalence classes spanning{" "}
        <strong>{row.spanBands ?? "—"}</strong> bands — from{" "}
        <code>{row.rarestClass}</code> to <code>{row.commonestClass}</code>. Every other tab
        in this dashboard renders this disorder with a single band.
      </p>
      <ol className={css.places}>
        {places.map((p) => (
          <li key={p.place} className={css.place}>
            <span className={css.placeName}>{p.place}</span>
            <span className={css.placeBands}>
              {p.bands.map((b) => (
                <span
                  key={b}
                  className={css.placeBand}
                  style={{ background: bandColor(b, classOrder.length, mode) }}
                  title={classOrder[b]}
                />
              ))}
              <span className={css.placeClass}>{classOrder[p.bands[0]]}</span>
            </span>
          </li>
        ))}
      </ol>
    </aside>
  );
}

/* ----------------------------------------------------------------------- shared ------- */

/** The viewer's resolved theme, watched. Three states, only two of which stamp an
 *  attribute, so both the stamp and the OS setting have to be observed. */
function useThemeMode(): "light" | "dark" {
  const [mode, setMode] = useState<"light" | "dark">(() =>
    typeof document === "undefined" ? "light" : resolveMode()
  );
  useEffect(() => {
    const sync = () => setMode(resolveMode());
    const mo = new MutationObserver(sync);
    mo.observe(document.documentElement, { attributes: true, attributeFilter: ["data-theme"] });
    const mq = window.matchMedia("(prefers-color-scheme: dark)");
    mq.addEventListener("change", sync);
    return () => { mo.disconnect(); mq.removeEventListener("change", sync); };
  }, []);
  return mode;
}

function Tile({
  label, value, note, tone,
}: { label: string; value: string; note: string; tone?: "over" | "under" | "warn" }) {
  return (
    <div className={css.tile}>
      <span className={css.tileLabel}>{label}</span>
      <span className={`${css.tileValue} ${tone ? css[tone] : ""}`}>{value}</span>
      <span className={css.tileNote}>{note}</span>
    </div>
  );
}

/** A skeleton with the shape of what is coming — not a spinner, so the layout does not
 *  jump when 214 kB of population data lands. */
function Skeleton() {
  return (
    <div className={css.root} aria-busy="true" aria-live="polite">
      <div className={`${css.caveat} ${css.shimmer}`} style={{ height: 64 }} />
      <div className={css.tiles}>
        {[0, 1, 2, 3].map((i) => (
          <div key={i} className={`${css.tile} ${css.shimmer}`} style={{ height: 104 }} />
        ))}
      </div>
      <div className={css.shimmer} style={{ height: 300, borderRadius: 10 }} />
      <span className={css.srOnly}>Loading the population dataset</span>
    </div>
  );
}
